[workspace]
resolver = "2"
members = [
    "crates/werust",
    "crates/werust-core",
    "crates/renderer",
    "crates/webview-renderer",
    "crates/native-renderer",
    "crates/fetcher",
    "crates/script-engine",
    "crates/werust-android/rust",
    "crates/werust-ios/rust",
]

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/wighawag/werust"
